#!/bin/bash

# Rofi powermenu modi
# This script is called by rofi in modi mode

# Icons (using Nerd Font icons)
shutdown='󰐥 Shutdown'
reboot='󰜉 Reboot'
lock=' Lock'
suspend='󰤄 Suspend'
logout='󰍃 Logout'

# If called with --help or --list, rofi is asking for entries
if [[ "$1" == "--help" ]] || [[ "$1" == "--list" ]]; then
    echo -e "$lock"
    echo -e "$suspend"
    echo -e "$logout"
    echo -e "$reboot"
    echo -e "$shutdown"
    exit 0
fi

# If called with a selection, execute the action
# Rofi passes the selected text as the first argument
selected="$1"

# Execute the selected action
case "$selected" in
    *"Lock"*)
        hyprlock
        ;;
    *"Suspend"*)
        mpc -q pause
        hyprlock
        systemctl suspend
        ;;
    *"Logout"*)
        hyprctl dispatch exit
        ;;
    *"Reboot"*)
        systemctl reboot
        ;;
    *"Shutdown"*)
        systemctl poweroff
        ;;
esac

