# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on


set -g automatic-rename off
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @catppuccin_flavor 'macchiato'
set -g @plugin 'christoomey/vim-tmux-adapter'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
#run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
