-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 20,
        border_size = 2,
        -- active border: gradient of two wal colors
        col = {
            active_border = {colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle=45},
            inactive_border = "rgba(595959aa)",
        },
        -- inactive border: dimmer color with some transparency
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
})
