###################################################
#                    Behavior                     #
###################################################
confirm_os_window_close 0
enable_audio_bell no
allow_remote_control yes

###################################################
#                      Shell                      #
###################################################
shell /usr/bin/zsh
shell_integration enabled
#shell bash --login -c "tmux attach || tmux new"

###################################################
#                   Appearance                    #
###################################################

include ~/.config/kitty/catppuccin.conf

font_size 12.0
font_family FiraCode Nerd Font
adjust_line_height 0

cursor_shape beam
cursor_trail 1

background_opacity 0.4
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}"
tab_bar_min_tabs 1
