# Window rules
# App placement
#swindowrulev2 = workspace 2, class:^(vesktop)$
#swindowrulev2 = float, class:^(vesktop)$, title:^(Picture-in-Picture)$
#swindowrulev2 = workspace 6, class:^(obsidian)$


# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

windowrule = match:class vesktop, workspace 6
windowrule = match:class virt-manager, workspace 5
windowrule = float on, match:class steam, workspace 1
windowrule = float on, match:class steam_app*, workspace 1
windowrule = float on, match:initial_title Guilty Gear -Strive-, workspace 1
windowrule = float on, match:class vesktop, match:initial_title Discord Popout
windowrule = float on, size 912 612 , match:class thunar
#windowrule = float on, size 912 612 , match:class obsidian

windowrule {
  name = move-kitty
  match:class = kitty
  animation = slide
  float = on
}
