# Applications
QT_QPA_PLATFORMTHEME=qt5ct
QT_STYLE_OVERRIDE=kvantum

XDG_CURRENT_DESKTOP=Hyprland
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=Hyprland
ELECTRON_OZONE_PLATFORM_HINT=x11 vesktop

XCURSOR_SIZE=24
HYPRCURSOR_SIZE=24

# Editors
EDITOR=micro
VISUAL=micro
