hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    --hl.exec_cmd("waybar")
    hl.exec_cmd("qs")
    hl.exec_cmd("swaync")
    hl.exec_cmd("vesktop")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("tldr --update")
    hl.exec_cmd("wl-paste --watch cliphist store")
end)
