exec_once=hyprpaper
exec_once=waybar
exec_once=swaync
exec_once=vesktop
exec_once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec_once=dbus-update-activation-environment --systemd --all
exec_once=systemctl --user start hyprpolkitagent
exec_once=tldr --update
exec_once=wl-paste --watch cliphist store
