env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,Kvantum
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = EDITOR,micro
env = VISUAL,micro
